### ISSUE TITLE
can't login as admin

### ISSUE THREAD

**Issue by hoedlmoser** [tete2soja/staytus#16]
upgraded to this fork, everything ok, but can not login as admin. this is running on Debian 12.

```
==> production.log <==
D, [2023-06-11T18:31:29.385737 #22135] DEBUG -- :   Delayed::Backend::ActiveRecord::Job Update All (0.7ms)  UPDATE `delayed_jobs` SET `delayed_jobs`.`locked_at` = '2023-06-11 16:31:29', `delayed_jobs`.`locked_by` = 'host:cup pid:22135' WHERE (((run_at <= '2023-06-11 16:31:29.383442' AND (locked_at IS NULL OR locked_at < '2023-06-11 12:31:29.383465')) OR locked_by = 'host:cup pid:22135') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC LIMIT 1
I, [2023-06-11T18:31:31.226970 #22133]  INFO -- : [2c22093a-eece-4e26-add5-810d5e31de55] Started POST "/admin/login" for <obfuscated> at 2023-06-11 18:31:31 +0200
I, [2023-06-11T18:31:31.228266 #22133]  INFO -- : [2c22093a-eece-4e26-add5-810d5e31de55] Processing by Admin::SessionsController#create as HTML
I, [2023-06-11T18:31:31.228469 #22133]  INFO -- : [2c22093a-eece-4e26-add5-810d5e31de55]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"<obfuscated>", "email"=>"<obfuscated>", "password"=>"[FILTERED]", "commit"=>"Login"}
D, [2023-06-11T18:31:31.231046 #22133] DEBUG -- : [2c22093a-eece-4e26-add5-810d5e31de55]   Site Load (0.5ms)  SELECT `sites`.* FROM `sites` ORDER BY `sites`.`id` ASC LIMIT 1
D, [2023-06-11T18:31:31.235865 #22133] DEBUG -- : [2c22093a-eece-4e26-add5-810d5e31de55]   User Load (0.3ms)  SELECT `users`.* FROM `users` WHERE `users`.`email_address` = '<obfuscated>' ORDER BY `users`.`id` ASC LIMIT 1
D, [2023-06-11T18:31:31.326717 #22133] DEBUG -- : [2c22093a-eece-4e26-add5-810d5e31de55]   LogLogins::Event Load (0.6ms)  SELECT `login_events`.`id` FROM `login_events` WHERE `login_events`.`user_type` = 'User' AND `login_events`.`user_id` = 1 AND `login_events`.`action` IN ('Success', 'Unblocked') ORDER BY `login_events`.`id` DESC LIMIT 1
D, [2023-06-11T18:31:31.335047 #22133] DEBUG -- : [2c22093a-eece-4e26-add5-810d5e31de55]    (0.5ms)  SELECT COUNT(*) FROM `login_events` WHERE `login_events`.`action` = 'Failed' AND (created_at > '2023-06-11 15:31:31.333727') AND `login_events`.`user_type` = 'User' AND `login_events`.`user_id` = 1 AND (id > 181)
D, [2023-06-11T18:31:31.336669 #22133] DEBUG -- : [2c22093a-eece-4e26-add5-810d5e31de55]   LogLogins::Event Load (0.4ms)  SELECT `login_events`.`id` FROM `login_events` WHERE `login_events`.`user_id` IS NULL AND `login_events`.`ip` = '<obfuscated> AND `login_events`.`action` IN ('Success', 'Unblocked') ORDER BY `login_events`.`id` DESC LIMIT 1
D, [2023-06-11T18:31:31.337924 #22133] DEBUG -- : [2c22093a-eece-4e26-add5-810d5e31de55]    (0.3ms)  SELECT COUNT(*) FROM `login_events` WHERE `login_events`.`action` = 'Failed' AND (created_at > '2023-06-11 15:31:31.336990') AND `login_events`.`user_id` IS NULL AND `login_events`.`ip` = '<obfuscated>' AND (id > 0)
D, [2023-06-11T18:31:31.340330 #22133] DEBUG -- : [2c22093a-eece-4e26-add5-810d5e31de55]   TRANSACTION (0.2ms)  BEGIN
D, [2023-06-11T18:31:31.340990 #22133] DEBUG -- : [2c22093a-eece-4e26-add5-810d5e31de55]   LogLogins::Event Create (0.4ms)  INSERT INTO `login_events` (`user_type`, `user_id`, `username`, `action`, `ip`, `created_at`) VALUES ('User', 1, '<obfuscated>', 'Success', '<obfuscated>', '2023-06-11 16:31:31')
D, [2023-06-11T18:31:31.342217 #22133] DEBUG -- : [2c22093a-eece-4e26-add5-810d5e31de55]   TRANSACTION (0.7ms)  COMMIT
I, [2023-06-11T18:31:31.353472 #22133]  INFO -- : [2c22093a-eece-4e26-add5-810d5e31de55] Completed 500 Internal Server Error in 125ms (ActiveRecord: 6.7ms | Allocations: 14532)
F, [2023-06-11T18:31:31.354607 #22133] FATAL -- : [2c22093a-eece-4e26-add5-810d5e31de55]   
[2c22093a-eece-4e26-add5-810d5e31de55] NoMethodError (undefined method `current_user=' for #<Admin::SessionsController:0x0000000000e150>

      self.current_user = user
          ^^^^^^^^^^^^^^^
Did you mean?  current_user):
[2c22093a-eece-4e26-add5-810d5e31de55]   
[2c22093a-eece-4e26-add5-810d5e31de55] app/controllers/admin/sessions_controller.rb:20:in `create'
[2c22093a-eece-4e26-add5-810d5e31de55] app/controllers/application_controller.rb:26:in `set_time_zone'

```

**Comment by nioupola** [comment]
Hello,

Did the initial creation account occur without issue?

**Comment by nioupola** [comment]
I found the source. I was old code. I replace with the new one from https://github.com/adamcooke/authie.
